
import com.transporters.Branch;
import com.transporters.Consignment;
import com.transporters.Database;
import com.transporters.HeadOffice;
import com.transporters.Truck;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author best1yash
 */
public class Manager extends javax.swing.JFrame {
    Database db;
    HeadOffice head_office;
    List<Branch> branch_list;
    List<Truck> truck_list;
    List<Consignment> consignment_list;

    int head_counter;
    int branch_counter;
    int truck_counter;
    int consignment_counter;
    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        try {
            Database.setIPAddress("localhost");
            db.setUrl(Database.getBranchURL());
            db.setUser("root");
            db.setPassword("alsk");

            Statement stmt = db.getConnection().createStatement();
            String query = "SELECT * FROM Lists;";
            ResultSet rs = stmt.executeQuery(query);
            byte[] buf;
            ObjectInputStream o;

            rs.next();
            buf = rs.getBytes("list");
            o = new ObjectInputStream(new ByteArrayInputStream(buf));
            branch_list = (ArrayList<Branch>) o.readObject();

            rs.next();
            buf = rs.getBytes("list");
            o = new ObjectInputStream(new ByteArrayInputStream(buf));
            truck_list = (ArrayList<Truck>) o.readObject();

            rs.next();
            buf = rs.getBytes("list");
            o = new ObjectInputStream(new ByteArrayInputStream(buf));
            consignment_list = (ArrayList<Consignment>) o.readObject();

            rs.next();
            buf = rs.getBytes("list");
            o = new ObjectInputStream(new ByteArrayInputStream(buf));
            head_office = (HeadOffice) o.readObject();

            query = "SELECT * ID_data;";
            rs = stmt.executeQuery(query);
            
            rs.next();
            head_counter = rs.getInt("counter");
            
            rs.next();
            branch_counter = rs.getInt("counter");
            
            rs.next();
            truck_counter = rs.getInt("counter");
            
            rs.next();
            consignment_counter = rs.getInt("counter");

        } catch (SQLException | IOException | ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_company_stats = new javax.swing.ButtonGroup();
        tp_manager = new javax.swing.JTabbedPane();
        p_administration = new javax.swing.JPanel();
        tp_administration = new javax.swing.JTabbedPane();
        p_hire = new javax.swing.JPanel();
        b_view_applicatns = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        l_employee_name = new javax.swing.JLabel();
        l_employee_address = new javax.swing.JLabel();
        l_branch = new javax.swing.JLabel();
        tf_employee_name = new javax.swing.JTextField();
        tf_employee_address = new javax.swing.JTextField();
        cmb_branch_list = new javax.swing.JComboBox();
        b_hire = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        p_buy_truck = new javax.swing.JPanel();
        l_model = new javax.swing.JLabel();
        l_plate_number = new javax.swing.JLabel();
        l_cost = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_truck_model = new javax.swing.JTextField();
        tf_plate_number = new javax.swing.JTextField();
        tf_cost = new javax.swing.JTextField();
        cmb_branch = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        p_fire = new javax.swing.JPanel();
        b_view_employee = new javax.swing.JButton();
        if_employee_list = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        tf_employee_id = new javax.swing.JTextField();
        l_employee_id = new javax.swing.JLabel();
        l_fire_reason = new javax.swing.JLabel();
        tf_fire_reason = new javax.swing.JTextField();
        b_fire = new javax.swing.JButton();
        Address = new javax.swing.JPanel();
        l_branch_name = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        l_contact = new javax.swing.JLabel();
        l_address = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        b_add_branch = new javax.swing.JButton();
        l_user_name = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        tf_user_name = new javax.swing.JTextField();
        tf_password = new javax.swing.JTextField();
        b_reset = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        l_set_ip = new javax.swing.JLabel();
        tf_set_ip = new javax.swing.JTextField();
        b_set_ip = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tf_charge = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        p_queries = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        cmb_query = new javax.swing.JComboBox();
        b_get_details = new javax.swing.JButton();
        tf_query = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        p_company_statistics = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        l_truck_plate_number = new javax.swing.JLabel();
        tf_truck_plate_num = new javax.swing.JTextField();
        b_get_truck_usage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_administration.setOpaque(false);

        tp_administration.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        p_hire.setPreferredSize(new java.awt.Dimension(800, 600));

        b_view_applicatns.setText("View Applicants");
        b_view_applicatns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_view_applicatnsActionPerformed(evt);
            }
        });

        l_employee_name.setText("Name");

        l_employee_address.setText("Addresss");

        l_branch.setText("Branch");

        tf_employee_name.setText("Employee Name");
        tf_employee_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_employee_nameFocusGained(evt);
            }
        });
        tf_employee_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_employee_nameActionPerformed(evt);
            }
        });

        tf_employee_address.setText("Employee Address");
        tf_employee_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_employee_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_employee_addressFocusLost(evt);
            }
        });

        cmb_branch_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        b_hire.setText("Hire");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Address", "Preferred Branch"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout p_hireLayout = new javax.swing.GroupLayout(p_hire);
        p_hire.setLayout(p_hireLayout);
        p_hireLayout.setHorizontalGroup(
            p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(p_hireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(p_hireLayout.createSequentialGroup()
                        .addGroup(p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_view_applicatns)
                            .addGroup(p_hireLayout.createSequentialGroup()
                                .addGroup(p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_employee_name)
                                    .addComponent(l_employee_address))
                                .addGroup(p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p_hireLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(tf_employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(l_branch))
                                    .addGroup(p_hireLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_employee_address, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_branch_list, 0, 180, Short.MAX_VALUE)
                                    .addComponent(b_hire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_hireLayout.setVerticalGroup(
            p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_view_applicatns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_employee_name)
                    .addComponent(tf_employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_branch)
                    .addComponent(cmb_branch_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_hireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_employee_address)
                    .addComponent(b_hire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_employee_address))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_administration.addTab("Add Employee", p_hire);

        l_model.setText("Model");

        l_plate_number.setText("Plate Number");

        l_cost.setText("Cost");

        jLabel4.setText("Assigned Branch");

        tf_truck_model.setText("Truck Model");

        tf_plate_number.setText("Plate Number");
        tf_plate_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_plate_numberActionPerformed(evt);
            }
        });

        tf_cost.setText("Cost");

        cmb_branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Add to fleet");

        javax.swing.GroupLayout p_buy_truckLayout = new javax.swing.GroupLayout(p_buy_truck);
        p_buy_truck.setLayout(p_buy_truckLayout);
        p_buy_truckLayout.setHorizontalGroup(
            p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_buy_truckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_model)
                    .addComponent(l_plate_number)
                    .addComponent(l_cost)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_truck_model, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(tf_plate_number)
                        .addComponent(tf_cost)
                        .addComponent(cmb_branch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_buy_truckLayout.setVerticalGroup(
            p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_buy_truckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_model)
                    .addComponent(tf_truck_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_plate_number)
                    .addComponent(tf_plate_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_cost)
                    .addComponent(tf_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_buy_truckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        tp_administration.addTab("Buy Trucks", p_buy_truck);

        p_fire.setPreferredSize(new java.awt.Dimension(800, 600));

        b_view_employee.setText("View Employees");
        b_view_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_view_employeeActionPerformed(evt);
            }
        });

        if_employee_list.setVisible(true);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        if_employee_list.getContentPane().add(jScrollPane5, java.awt.BorderLayout.CENTER);

        tf_employee_id.setText("Employee Id");

        l_employee_id.setText("Employee Id");

        l_fire_reason.setText("Reason for firing");

        tf_fire_reason.setText("Employee's services are terminated due to following causes:");

        b_fire.setText("Fire");

        javax.swing.GroupLayout p_fireLayout = new javax.swing.GroupLayout(p_fire);
        p_fire.setLayout(p_fireLayout);
        p_fireLayout.setHorizontalGroup(
            p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_fireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(if_employee_list)
                    .addComponent(jSeparator2)
                    .addGroup(p_fireLayout.createSequentialGroup()
                        .addComponent(b_view_employee)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p_fireLayout.createSequentialGroup()
                        .addGroup(p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_employee_id)
                            .addComponent(l_fire_reason))
                        .addGap(54, 54, 54)
                        .addGroup(p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_fire_reason, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addGroup(p_fireLayout.createSequentialGroup()
                                .addGroup(p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b_fire)
                                    .addComponent(tf_employee_id, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        p_fireLayout.setVerticalGroup(
            p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_fireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_view_employee)
                .addGap(18, 18, 18)
                .addComponent(if_employee_list, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_employee_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_employee_id))
                .addGap(18, 18, 18)
                .addGroup(p_fireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fire_reason, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_fire_reason))
                .addGap(18, 18, 18)
                .addComponent(b_fire)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_administration.addTab("Remove Employee", p_fire);

        l_branch_name.setText("Branch Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        l_contact.setText("Contact");

        l_address.setText("Address");

        b_add_branch.setText("Add Branch");

        l_user_name.setText("User Name");

        l_password.setText("Password");

        b_reset.setText("Reset");

        l_set_ip.setText("IP Address");

        tf_set_ip.setText("198.16.1.1");
        tf_set_ip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_set_ipFocusGained(evt);
            }
        });

        b_set_ip.setText("Set IP Address");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Charge/Volume");

        jButton3.setText("Set Charge/Volume");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout AddressLayout = new javax.swing.GroupLayout(Address);
        Address.setLayout(AddressLayout);
        AddressLayout.setHorizontalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddressLayout.createSequentialGroup()
                        .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddressLayout.createSequentialGroup()
                                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_branch_name)
                                    .addComponent(l_contact)
                                    .addComponent(l_address))
                                .addGap(18, 18, 18)
                                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jTextField3)))
                                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddressLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l_user_name)
                                            .addComponent(l_password))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_user_name, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(tf_password)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressLayout.createSequentialGroup()
                                        .addGap(213, 213, 213)
                                        .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(b_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b_add_branch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))))
                            .addGroup(AddressLayout.createSequentialGroup()
                                .addComponent(l_set_ip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_set_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_set_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_charge)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddressLayout.setVerticalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_branch_name)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_user_name)
                    .addComponent(tf_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_contact)
                    .addComponent(l_password)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddressLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(b_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_add_branch))
                    .addGroup(AddressLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_address))))
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddressLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddressLayout.createSequentialGroup()
                                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_set_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_set_ip))
                                .addGap(18, 18, 18)
                                .addComponent(b_set_ip))
                            .addGroup(AddressLayout.createSequentialGroup()
                                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tf_charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tp_administration.addTab("Miscellaneous", Address);

        javax.swing.GroupLayout p_administrationLayout = new javax.swing.GroupLayout(p_administration);
        p_administration.setLayout(p_administrationLayout);
        p_administrationLayout.setHorizontalGroup(
            p_administrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_administrationLayout.createSequentialGroup()
                .addComponent(tp_administration, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p_administrationLayout.setVerticalGroup(
            p_administrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_administrationLayout.createSequentialGroup()
                .addComponent(tp_administration, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        tp_manager.addTab("Administration", p_administration);

        p_queries.setOpaque(false);

        jInternalFrame1.setVisible(true);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        cmb_query.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consignment Details", "Truck Details" }));
        cmb_query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_queryActionPerformed(evt);
            }
        });

        b_get_details.setText("Get Details");

        tf_query.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_queryFocusGained(evt);
            }
        });

        jLabel2.setText("Details");

        javax.swing.GroupLayout p_queriesLayout = new javax.swing.GroupLayout(p_queries);
        p_queries.setLayout(p_queriesLayout);
        p_queriesLayout.setHorizontalGroup(
            p_queriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_queriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_queriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1)
                    .addGroup(p_queriesLayout.createSequentialGroup()
                        .addGroup(p_queriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_queriesLayout.createSequentialGroup()
                                .addComponent(cmb_query, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(p_queriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_query, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_get_details, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(0, 376, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_queriesLayout.setVerticalGroup(
            p_queriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_queriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_queriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_query, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_query, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_get_details)
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        tp_manager.addTab("Queries", p_queries);

        p_company_statistics.setOpaque(false);

        l_truck_plate_number.setText("Truck Plate Number");

        b_get_truck_usage.setText("Get Truck Usage");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Branch");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButton1.setText("Average Truck Idle Time");

        jRadioButton2.setText("Average Consigment Waiting Time");

        jRadioButton3.setText("Branch Consignment Handling");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Query");

        javax.swing.GroupLayout p_company_statisticsLayout = new javax.swing.GroupLayout(p_company_statistics);
        p_company_statistics.setLayout(p_company_statisticsLayout);
        p_company_statisticsLayout.setHorizontalGroup(
            p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(p_company_statisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_company_statisticsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_company_statisticsLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(p_company_statisticsLayout.createSequentialGroup()
                                .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))))
                    .addGroup(p_company_statisticsLayout.createSequentialGroup()
                        .addComponent(l_truck_plate_number)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_get_truck_usage)
                            .addComponent(tf_truck_plate_num, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_company_statisticsLayout.setVerticalGroup(
            p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_company_statisticsLayout.createSequentialGroup()
                .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_company_statisticsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_company_statisticsLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_company_statisticsLayout.createSequentialGroup()
                        .addGroup(p_company_statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_truck_plate_number)
                            .addComponent(tf_truck_plate_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_get_truck_usage))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_manager.addTab("Company Statistics", p_company_statistics);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/protectedimage.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 150));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 150));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 150));

        b_back.setText("Back");
        b_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_manager, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(b_back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_employee_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_employee_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_employee_nameActionPerformed

    private void b_view_applicatnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_view_applicatnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_view_applicatnsActionPerformed

    private void tf_plate_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_plate_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_plate_numberActionPerformed

    private void b_view_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_view_employeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_view_employeeActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void b_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_backMouseClicked
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_b_backMouseClicked

    private void tf_employee_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_employee_nameFocusGained
        tf_employee_name.setText("");
    }//GEN-LAST:event_tf_employee_nameFocusGained

    private void tf_employee_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_employee_addressFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_employee_addressFocusLost

    private void tf_employee_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_employee_addressFocusGained
        tf_employee_address.setText("");
    }//GEN-LAST:event_tf_employee_addressFocusGained

    private void tf_set_ipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_set_ipFocusGained
        tf_set_ip.setText("");
    }//GEN-LAST:event_tf_set_ipFocusGained

    private void cmb_queryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_queryActionPerformed
        if(cmb_query.getSelectedIndex() == 0){
            tf_query.setText("Consignment Id");
        }else if(cmb_query.getSelectedIndex() == 1){
            tf_query.setText("Truck Id");
        }
    }//GEN-LAST:event_cmb_queryActionPerformed

    private void tf_queryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_queryFocusGained
        tf_query.setText("");
        
    }//GEN-LAST:event_tf_queryFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Address;
    private javax.swing.JButton b_add_branch;
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_fire;
    private javax.swing.JButton b_get_details;
    private javax.swing.JButton b_get_truck_usage;
    private javax.swing.JButton b_hire;
    private javax.swing.JButton b_reset;
    private javax.swing.JButton b_set_ip;
    private javax.swing.JButton b_view_applicatns;
    private javax.swing.JButton b_view_employee;
    private javax.swing.ButtonGroup bg_company_stats;
    private javax.swing.JComboBox cmb_branch;
    private javax.swing.JComboBox cmb_branch_list;
    private javax.swing.JComboBox cmb_query;
    private javax.swing.JInternalFrame if_employee_list;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel l_address;
    private javax.swing.JLabel l_branch;
    private javax.swing.JLabel l_branch_name;
    private javax.swing.JLabel l_contact;
    private javax.swing.JLabel l_cost;
    private javax.swing.JLabel l_employee_address;
    private javax.swing.JLabel l_employee_id;
    private javax.swing.JLabel l_employee_name;
    private javax.swing.JLabel l_fire_reason;
    private javax.swing.JLabel l_model;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_plate_number;
    private javax.swing.JLabel l_set_ip;
    private javax.swing.JLabel l_truck_plate_number;
    private javax.swing.JLabel l_user_name;
    private javax.swing.JPanel p_administration;
    private javax.swing.JPanel p_buy_truck;
    private javax.swing.JPanel p_company_statistics;
    private javax.swing.JPanel p_fire;
    private javax.swing.JPanel p_hire;
    private javax.swing.JPanel p_queries;
    private javax.swing.JTextField tf_charge;
    private javax.swing.JTextField tf_cost;
    private javax.swing.JTextField tf_employee_address;
    private javax.swing.JTextField tf_employee_id;
    private javax.swing.JTextField tf_employee_name;
    private javax.swing.JTextField tf_fire_reason;
    private javax.swing.JTextField tf_password;
    private javax.swing.JTextField tf_plate_number;
    private javax.swing.JTextField tf_query;
    private javax.swing.JTextField tf_set_ip;
    private javax.swing.JTextField tf_truck_model;
    private javax.swing.JTextField tf_truck_plate_num;
    private javax.swing.JTextField tf_user_name;
    private javax.swing.JTabbedPane tp_administration;
    private javax.swing.JTabbedPane tp_manager;
    // End of variables declaration//GEN-END:variables
}
